---
config:
  layout: elk
  class:
    hideEmptyMembersBox: true
  theme: redux
  look: neo
---
classDiagram
direction TB
    class Card {
	    +getName() String
    }
    class Player {
	    +getName() String
	    +getChestGems() int
	    +getSackGems() int
	    +getChoice() PlayerChoice
	    +addSackGems(gems: int)
	    +resetPlayer()
	    +choose(choice: PlayerChoice)
    }
    class PlayerCpu {
    }
    class RoundEffect {
	    +isRoundOver() boolean
	    +modifyGems(gems: int) int
    }
    class Deck {
	    +drawCard() Card
	    +isDeckEmpty() boolean
	    +deckSize() int
	    +shuffle()
    }
    class Turn {
	    +getTurnPlayer() Player
	    +getDrawnCard() Card
	    +executeDrawPhase()
	    +executeDecisionPhase()
    }
    class RelicCard {
	    +getGems() int
    }
    class TrapCard {
	    +getTrapType() TypeTrapCard
    }
    class TreasureCard {
	    +getGems() int
    }
    class Round {
	    +getNextTurn() Turn
	    +currentTurnNumber() int
	    +getDrawnCards() List~Card~
	    +getPathGems() int
	    +addCardToPath(card: Card)
	    +getDeck() Deck
    }
    class Game {
	    +getNextRound() Round
	    +currentRoundNumber() int
	    +isGameOver() boolean
    }
    class PlayerChoice {
    }
    class TypeTrapCard {
    }

	<<interface>> Card
	<<interface>> Player
	<<interface>> PlayerCpu
	<<interface>> RoundEffect
	<<interface>> Deck
	<<interface>> Turn
	<<interface>> RelicCard
	<<interface>> TrapCard
	<<interface>> TreasureCard
	<<interface>> Round
	<<interface>> Game
	<<interface>> PlayerChoice
	<<interface>> TypeTrapCard

    TrapCard --|> Card
    RelicCard --|> Card
    TreasureCard --|> Card
    PlayerCpu --|> Player
    Game *-- Round : <br>
    Round *-- Turn : <br>
    Round *-- Deck : <br>
    Round *-- RoundEffect : <br>
    Round *-- Card : <br>
    Deck *-- Card : <br>
    Round --> Player : <br>
    Turn --> Player : <br>
    Turn --> Card : <br>
    Player --> PlayerChoice : <br>
    TrapCard --> TypeTrapCard : <br>
